--PART B3
--TODO 1: Adding Keys

ALTER TABLE VOTE MODIFY VOTER_ID CHAR(10) PRIMARY KEY; -- Already declared (B2 TODO: 1) PRIMARY KEY



ALTER TABLE CONSTITUENCY ADD VOTER_ID CHAR(10)

ALTER TABLE CONSTITUENCY
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTE(VOTER_ID);   -- Vote(voter_id) ---> Constituency(voter_id) = 1:M
														-- Same we can do from Vote table which will 1:M




ALTER TABLE VOTE
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID);



ALTER TABLE VOTER MODIFY VOTER_ID CHAR(10) PRIMARY KEY; -- Already declared (B2 TODO: 2) PRIMARY KEY




ALTER TABLE CONSTITUENCY MODIFY CONSTITUENCY_ID char(10) PRIMARY KEY; -- Already declared (B2 TODO: 3)  PRIMARY KEY













ALTER TABLE VOTE 
ADD PRIMARY KEY(VOTER_ID); 


 ALTER TABLE VOTER
ADD PRIMARY KEY(VOTER_ID);


ALTER TABLE CONSTITUENCY ADD VOTER_ID CHAR(10);

ALTER TABLE CONSTITUENCY
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTE(VOTER_ID);


ALTER TABLE VOTE
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID);